version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/project3
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - redis
      - database

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  database:
    image: "mariadb:latest"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: project3
    ports:
      - "3306:3306"
